- hosts: masters
  tasks:
  - name: setup_ocp_admin_roles | Login as system:admin
    shell: oc login -u system:admin -n default --config=/etc/origin/master/admin.kubeconfig
  - name: fuse72 | Install Fuse 7.2 Image Streams
    shell: curl https://raw.githubusercontent.com/jboss-fuse/application-templates/application-templates-2.1.fuse-720018-redhat-00001/fis-image-streams.json | oc replace --force -f - -n openshift
    ignore_errors: yes
  - name: jbosseap72 | Install JBoss EAP 7.2 Templates
    shell: curl https://raw.githubusercontent.com/jboss-container-images/jboss-eap-7-openshift-image/EAP_720/templates/{{item}} | oc replace --force -f - -n openshift
    with_items:
    - eap72-amq-persistent-s2i.json
    - eap72-amq-s2i.json
    - eap72-basic-s2i.json
    - eap72-https-s2i.json
    - eap72-image-stream.json
    - eap72-mongodb-persistent-s2i.json
    - eap72-mongodb-s2i.json
    - eap72-mysql-persistent-s2i.json
    - eap72-mysql-s2i.json
    - eap72-postgresql-persistent-s2i.json
    - eap72-postgresql-s2i.json
    - eap72-sso-s2i.json
    - eap72-starter-s2i.json
    - eap72-third-party-db-s2i.json
    - eap72-tx-recovery-s2i.json
  - name: fuse72 | Install Fuse 7.2 Templates
    shell: curl https://raw.githubusercontent.com/jboss-fuse/application-templates/application-templates-2.1.fuse-720018-redhat-00001/quickstarts/{{item}} | oc replace --force -f - -n openshift
    with_items:
    - eap-camel-amq-template.json
    - eap-camel-cdi-template.json
    - eap-camel-cxf-jaxrs-template.json
    - eap-camel-cxf-jaxws-template.json
    - eap-camel-jpa-template.json
    - karaf-camel-amq-template.json
    - karaf-camel-log-template.json
    - karaf-camel-rest-sql-template.json
    - karaf-cxf-rest-template.json
    - spring-boot-camel-amq-template.json
    - spring-boot-camel-config-template.json
    - spring-boot-camel-drools-template.json
    - spring-boot-camel-infinispan-template.json
    - spring-boot-camel-rest-sql-template.json
    - spring-boot-camel-teiid-template.json
    - spring-boot-camel-template.json
    - spring-boot-camel-xa-template.json
    - spring-boot-camel-xml-template.json
    - spring-boot-cxf-jaxrs-template.json
    - spring-boot-cxf-jaxws-template.json
    ignore_errors: yes
  - name: fuse72 | Install Fuse 7.2 Console Template
    shell: curl https://raw.githubusercontent.com/jboss-fuse/application-templates/application-templates-2.1.fuse-720018-redhat-00001/fis-console-cluster-template.json | oc replace --force -f - -n openshift
    ignore_errors: yes
  - name: amq72 | Install AMQ 7.2 Image-Streams
    shell: |
      curl https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.0.GA/amq-broker-7-image-streams.yaml | oc replace --force -f - -n openshift
      curl https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.0.GA/amq-broker-7-scaledown-controller-image-streams.yaml | oc replace --force -f - -n openshift
    ignore_errors: yes
  - name: amq72 | Install AMQ 7.2 Templates
    shell: curl https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.0.GA/templates/{{item}} | oc replace --force -f - -n openshift
    with_items:
    - amq-broker-72-basic.yaml
    - amq-broker-72-ssl.yaml
    - amq-broker-72-custom.yaml
    - amq-broker-72-persistence.yaml
    - amq-broker-72-persistence-ssl.yaml
    - amq-broker-72-persistence-clustered.yaml
    - amq-broker-72-persistence-clustered-ssl.yaml
    ignore_errors: yes
  - name: 3scale24 | Install 3scale 2.4
    shell: curl https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.4.0.GA/amp/amp.yml | oc replace --force -f - -n openshift
    ignore_errors: yes
  - name: pam73 | Install Process Automation Manager 7.3 Image Streams
    shell: curl https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/7.3.0.GA/rhpam73-image-streams.yaml | oc replace --force -f - -n openshift
    ignore_errors: yes
  - name: pam73 | Install Process Automation Manager 7.3 Templates
    shell: curl https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/7.3.0.GA/templates/{{item}} | oc replace --force -f - -n openshift
    with_items:
    - rhpam73-authoring-ha.yaml
    - rhpam73-authoring.yaml
    - rhpam73-kieserver-externaldb.yaml
    - rhpam73-kieserver-mysql.yaml
    - rhpam73-kieserver-postgresql.yaml
    - rhpam73-managed.yaml
    - rhpam73-prod-immutable-kieserver.yaml
    - rhpam73-prod-immutable-monitor.yaml
    - rhpam73-prod.yaml
    - rhpam73-trial-ephemeral.yaml
    ignore_errors: yes
  - name: dm73 | Install Decision Manager 7.3 Image Streams
    shell: curl https://raw.githubusercontent.com/jboss-container-images/rhdm-7-openshift-image/7.3.0.GA/rhdm73-image-streams.yaml | oc replace --force -f - -n openshift
    ignore_errors: yes
  - name: dm73 | Install Decision Manager 7.3 Templates
    shell: curl https://raw.githubusercontent.com/jboss-container-images/rhdm-7-openshift-image/7.3.0.GA/templates/{{item}} | oc replace --force -f - -n openshift
    with_items:
    - rhdm73-authoring-ha.yaml
    - rhdm73-authoring.yaml
    - rhdm73-kieserver.yaml
    - rhdm73-prod-immutable-kieserver.yaml
    - rhdm73-trial-ephemeral.yaml
    ignore_errors: yes
  - name: sso73 | Install SSO 7.3 Templates
    shell: curl https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/v7.3.0.GA/templates/{{item}} | oc replace --force -f - -n openshift
    with_items:
    - sso73-https.json
    - sso73-image-stream.json
    - sso73-mysql-persistent.json
    - sso73-mysql.json
    - sso73-postgresql-persistent.json
    - sso73-postgresql.json
    - sso73-x509-https.json
    - sso73-x509-mysql-persistent.json
    - sso73-x509-postgresql-persistent.json
    ignore_errors: yes
  - name: import_images | Import all image streams
    shell: oc get is -n openshift --no-headers=true | awk '{print $1}' | xargs -I{} oc import-image {} -n openshift --insecure=true --all=true
    retries: 3
    delay: 5
    ignore_errors: yes
