apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi-glusterfs.apps.ocplabs.com"
  restuser: "admin"
  volumetype: "replicate:3"
  clusterid: "{{heketi_clusterid.stdout_lines[0]}}"
  volumeoptions: "client.ssl off, server.ssl off, features.cache-invalidation on, performance.nl-cache on"
