apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-file
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi-glusterfs.apps.ocplabs.com"
  restuser: "admin"
  volumetype: "replicate:3"
  clusterid: "{{heketi_clusterid.stdout_lines[0]}}"
  volumenameprefix: gf
  volumeoptions: "client.ssl off, server.ssl off, user.heketi.arbiter true"
reclaimPolicy: Delete
