- hosts: localhost
  gather_facts: true
  tasks:
  - name: configure_docker | Configure Docker registries
    template:
      src: ocplabs-containers-registries.conf
      dest: /etc/containers/registries.conf
      owner: root
      group: root
      mode: 0640
    register: container_config
  - name: configure_docker | Stop Docker
    systemd:
      name: docker
      state: stopped
    when: container_config.changed
  - name: configure_docker | Start Docker
    systemd:
      name: docker
      state: started
    when: container_config.changed
  - name: check_docker_images | Check if Docker Images exist in repository
    shell: |
      curl -s -X GET --header 'Accept: application/json' 'http://{{ocp_docker_registry_host}}:8081/service/siesta/rest/beta/search/assets?repository=ocplabs-docker&name={{item.image.replace("/","%2F")}}&docker.imageTag={{item.tags[0]}}' | grep '"id" :' 
    register: docker_images_missing
    with_items: "{{container_catalog.containers}}"
    ignore_errors: yes
  - name: show_missing_docker_images | Show missing docker images
    debug: msg="{{docker_images_missing.results}}"   
  - name: pull_docker_images | Pull Docker Images
    shell: |
      docker pull {{ ocp_docker_registry_host }}:{{ ocp_docker_registry_port }}/{{item.item.image}}:{{item.item.tags[0]}}
      docker pull {{ ocp_docker_registry_host }}:{{ ocp_docker_registry_port }}/{{item.item.image}}:{{item.item.tags[1]}}
      docker pull {{ ocp_docker_registry_host }}:{{ ocp_docker_registry_port }}/{{item.item.image}}:latest
      docker images | grep "{{item.item.image}}" | awk '{print $3}' | sort -u | xargs -I{} docker rmi {} -f
    when: item.failed == True
    with_items: "{{docker_images_missing.results}}" 
    ignore_errors: yes
